publish_to: none

name: dev_mirror
description: Development proxy for accessing private APIs.
version: 1.1.1
homepage: https://github.com/Zekfad/dev-mirror

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  collection: ^1.16.0
  dotenv: ^3.0.0
  uri: ^1.0.0
dev_dependencies:
  zekfad_lints: ^1.1.0
