name: dev_mirror
description: Development mirror proxy.
version: 1.0.0
homepage: https://github.com/Zekfad/dev-mirror

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  dotenv: ^3.0.0
  uri: ^1.0.0
dev_dependencies:
  lints: ^1.0.0
