publish_to: none

name: dev_mirror
description: Development proxy for accessing private APIs.
version: 1.3.0
homepage: https://github.com/Zekfad/dev-mirror

environment:
  sdk: '>=3.1.0-0 <4.0.0'

dependencies:
  dotenv: ^4.1.0
  uri: ^1.0.0
dev_dependencies:
  zekfad_lints: ^2.1.0
